### ISSUE TITLE
Review 1 (ozan)

### ISSUE THREAD

**Issue by ozanh** [asalih/bin-magicbytes#1]
cc @hpolatyuruk @yakuter 
Thanks Ahmet, let me write down some issues I found at first glance.

1. `ArgumentError` type should not be exported, because all exports were predefined in the code challenge.
2. Do we really need `searchContext` type to pass paths and other stuff? `onMatch` callback and `metas` do not change and not dynamic so we can just pass the file paths over channel and `searchContext` is not required. Passing metas and onMatch to `worker` function when it is created is enough. In addition; wg field in `searchContext` is not used so it is useless.
3. You handled nil items in `metas` but it must not have nil items in slice so checking if there is a nil item in it can hide the problem with the given arguments. It should be removed from the readme as well.
4. If we don not create new error from an error, log.Printf is enough to print formatted message. There are other same uses to be fixed.
https://github.com/asalih/bin-magicbytes/blob/3f7503bd4b213dac5839e2a4f0958968e1b56d86/magicbytes/magicbytes.go#L78
5. As label `loop` is only used with continue statement, label can be dropped.
https://github.com/asalih/bin-magicbytes/blob/3f7503bd4b213dac5839e2a4f0958968e1b56d86/magicbytes/worker.go#L12-L23
6. Following `select` statement can be removed because you already check the context in for loop below.
https://github.com/asalih/bin-magicbytes/blob/3f7503bd4b213dac5839e2a4f0958968e1b56d86/magicbytes/file_search.go#L11-L16
7. You should use `io.SeekStart` for readability instead of zero like this `_, e := f.Seek(meta.Offset, io.SeekStart)`
https://github.com/asalih/bin-magicbytes/blob/3f7503bd4b213dac5839e2a4f0958968e1b56d86/magicbytes/file_search.go#L55
I have not checked the test files yet. May be after issues are fixed.

**Comment by asalih** [comment]
1. Correct thank you. It is still just an error, no need to export.
2. Yes this can be unnecessary but I am passing needed refs using refs, but your point is valid so it can be removed thank you! Removed as well.
3. Yes you are correct but it will reduce the users' mistakes. It's little bit on who is going to use it. For instance if I am going to only use this package only, I definitely take care of nil values but if I am going to serve this as a package, I think I can spend a little bit of time on null check. But read me fixed thank you.
4-5 and 6. Removed, thank you.
7. Instead of a magic number using this helpful, thanks.
